spring:
  application:
    name: hira
  datasource:
    url: jdbc:postgresql://localhost:5432/hira
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
